<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" type="text/javascript"></script>
    <div>
        <h3>Delivered packages</h3>
        <canvas id="countries" width="1200" height="400"></canvas>
    </div>
<div style="display: flex ; flex-direction: row; justify-content:space-around ; margin-top: 100px;">
    <div >
        <h3>Number of customers registered per month</h3>
        <canvas id="count" width="700" height="400"></canvas>
    </div>
    <div >
        <h3>Number of tickets created on packages</h3>
        <canvas id="co" width="600" height="400"></canvas>
    </div>
</div>

<script>
    var labels = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ];

    var data = {
        labels: labels,
        datasets: [{
            label: 'My First dataset',
            Color: '#878BB6',
            data: [0, 12, 15, 20, 30, 55, 73, 18, 40, 37, 23,88],
        }]
    };
    var countries= document.getElementById("countries").getContext("2d");
    new Chart(countries).Line(data);
</script>
<script>
    var labels = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ];

    var data = {
        labels: labels,
        datasets: [{
            label: 'My First dataset',
            Color: '#154360',
            data: [0, 1, 5, 2, 20, 10, 7, 8, 9, 3, 7,2],
        }]
    };
    var count= document.getElementById("count").getContext("2d");
    new Chart(count).Bar(data);
</script>
<script>
        var labels = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
        ];

        var data = {
        labels: labels,
        datasets: [{
        label: 'My First dataset',
        Color: '#154360',
        data: [0, 10, 5, 2, 1, 3, 7,2, 8, 0, 6,2],
    }]
    };
        var co= document.getElementById("co").getContext("2d");
        new Chart(co).Bar(data);
</script>
