<div class="container" style="width: 50%">
    <div class="row">
        <div class="col-md-8">
            <form name="addData" method="post" id="addData" class="form"
                  action="<?php echo $this->getFormAction(); ?>"
                  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset">
                    <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Personal Information')) ?></span></legend>
                    <fieldset class="fieldset row">
                        <div class="fields col-md-6">
                            <div class="field name required">
                                <label class="label" for="title"><span><?= $block->
                                        escapeHtmlAttr(__('First Name')) ?></span></label>
                                <div class="control">
                                    <input name="First_Name" id="First_Name" title="First_Name" value="" class="input-text" type="text">
                                </div>
                            </div>
                            <div class="field name required">
                                <label class="label" for="title"><span><?= $block->
                                        escapeHtmlAttr(__('Last Name')) ?></span></label>
                                <div class="control">
                                    <input name="Last_Name" id="Last_Name" title="Last_Name" value="" class="input-text" type="text">
                                </div>
                            </div>

                            <div class="field name required">
                                <label class="label" for="title"><span><?= $block->
                                        escapeHtmlAttr(__('UserName')) ?></span></label>
                                <div class="control">
                                    <input name="UserName" id="UserName" title="UserName" value="" class="input-text" type="text">
                                </div>
                            </div>
                            <div class="field name required">
                                <label class="label" for="title"><span><?= $block->
                                        escapeHtmlAttr(__('Email')) ?></span></label>
                                <div class="control">
                                    <input name="email" id="email" title="Email" value=""
                                           class="input-text" type="text"
                                           data-validate="{required:true, 'validate-email':true}">
                                </div>
                            </div>
                            <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                                <label class="label" for="password"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                                <div class="control">
                                    <input type="Password" class="input-text" name="Password" id="Password"
                                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                           data-validate="{required:true, 'validate-admin-password':true}"
                                           autocomplete="off">
                                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                        <div id="password-strength-meter" class="password-strength-meter">
                                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                    <?= $block->escapeHtml(__('No Password')) ?>
                </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field confirmation required">
                                <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                                <div class="control">
                                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#Password'}" autocomplete="off">
                                </div>
                            </div>
                    </fieldset>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                                escapeHtmlAttr(__('Create an Account')) ?></span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
