<?php

use Norsys\Ticket\Block\Adminhtml\Ticket\View\Info;

/** @var Info $block */
$ticket = $block->getTicket();
$customer = $block->getCustomer();
$user = $block->getUser();
?>
<?php if ($ticket !== NULL): ?>
    <section class="admin__page-section ">
        <div class="admin__page-section-title">
        <span
            class="title"><?= $block->escapeHtml(__('Customer Account Information')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item ">
                <?php /* Customer Account Information */ ?>
                <div class="admin__page-section-item-content">
                    <?php if ($customer->getEmail() !== NULL) : ?>
                        <table class="admin__table-secondary ">
                            <tr>
                                <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                                <td><?= $customer->getFirstname() . ' ' . $customer->getLastname() ?></td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Customer Email')) ?></th>
                                <td>
                                    <span><?= $block->escapeHtml($customer->getEmail()) ?></span>
                                </td>
                            </tr>
                        </table>
                    <?php else : ?>
                        <table class="admin__table-secondary ">
                            <tr>
                                <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                                <td><?= $user->getFirstname() . ' ' . $user->getLastname() ?></td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Customer Email')) ?></th>
                                <td>
                                    <span><?= $block->escapeHtml($user->getEmail()) ?></span>
                                </td>
                            </tr>
                        </table>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </section>
    <section class="admin__page-section ">
        <div class="admin__page-section-title">
        <span
            class="title"><?= $block->escapeHtml(__('Ticket Information')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item">
                <?php /* Ticket Information */ ?>
                <div class="admin__page-section-item-title">
                <span class="title">
                    <?= $block->escapeHtml(__('Ticket # %1', $ticket->getTicketId())) ?>
                </span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary ">
                        <tr>
                            <th><?= $block->escapeHtml(__('Ticket Title')) ?></th>
                            <td><?= $ticket->getTitle() ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Ticket Status')) ?></th>
                            <td>
                                <span><?= $block->escapeHtml($ticket->getStatus()) ?></span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Ticket Type')) ?></th>
                            <td>
                                <span><?= $block->escapeHtml($ticket->getType()) ?></span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Ticket Emergency')) ?></th>
                            <td>
                                <span><?= $block->escapeHtml($ticket->getEmergency()) ?></span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Ticket Impact')) ?></th>
                            <td>
                                <span><?= $block->escapeHtml($ticket->getImpact()) ?></span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Ticket Priority')) ?></th>
                            <td>
                                <span><?= $block->escapeHtml($ticket->getPriority()) ?></span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Created At')) ?></th>
                            <td>
                                <span><?= $block->escapeHtml($ticket->getCreatedAt()) ?></span>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <section class="admin__page-section ">
        <div class="admin__page-section-title">
        <span
            class="title"><?= $block->escapeHtml(__('Ticket Description')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item">
                <span><?= $block->escapeHtml($ticket->getDescription()) ?></span>
            </div>
        </div>
    </section>
    <section class="admin__page-section ">
        <div class="admin__page-section-title">
        <span
            class="title"><?= $block->escapeHtml(__('Ticket Attachment')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <?php /* Ticket Attachment */ ?>
            <?php $attachments = $block->getTicketAttachment(); ?>
            <?php if (isset($attachments) && count($attachments)) : ?>
                <?php foreach ($attachments as $_attachment) : ?>
                    <div class="admin__page-section-item">
                        <img
                            src="<?= $block->getPath() . $_attachment->getFile() ?>"
                            style="width: 30%;">
                    </div>
                <?php endforeach; ?>
            <?php else : ?>
                <div class="message info empty">
                    <span><?= $block->escapeHtml(__('This customer has no placed attachments.')) ?></span>
                </div>
            <?php endif ?>
        </div>
    </section>
<?php else : ?>
    <td> <?= $block->escapeHtml(__('No information for the moment')) ?></td>
<?php endif; ?>
